export default {
  items: [
    {
      name: "Carrera black and gold sunglasses",
      category: "Sunglasses",
      id: "1",
      price: "175",
      size: "58-16-145",
      brand: "Carrera",
      url: "/img/brown-carrera.png",
      url1: "/img/brown-carrera1.png",
      url2: "/img/brown-carrera2.png",
      description:
        "Lightweight Carrera black and gold sunglasses. Funky shape and very in at the moment.",
    },
    {
      name: "Ralph Lauren big round black sunglasses",
      category: "Sunglasses",
      id: "2",
      price: "199",
      size: "Oversized",
      brand: "Ralph Lauren",
      url: "/img/roundRL.png",
      url1: "/img/roundRL1.png",
      url2: "/img/roundRL2.png",
      url3: "/img/roundRL3.png",
      description:
        "Bold RL black sunglasses with big personality. Definitely a statement piece. Lots of sun protection and coverage. Fun and funky.",
    },
    {
      name: "Prada black and gold sunglasses",
      category: "Sunglasses",
      id: "3",
      price: "325",
      size: "Oversized 62 - 13 - 145",
      brand: "DIFF",
      url: "/img/pradaBlk.png",
      url1: "/img/pradaBlk1.png",
      url2: "/img/pradaBlk2.png",
      url3: "/img/pradaBlk3.png",
      description:
        "Prada black and gold sunglasses with gold trim on top. Super fashionable and fun shape.",
    },
    {
      name: "Kate Spade blue & gold glasses",
      category: "Glasses",
      id: "5",
      price: "165",
      size: "One size",
      brand: "Kate Spade",
      url: "/img/kateSpadeBlue.png",
      url1: "/img/kateSpadeBlue1.png",
      url2: "/img/kateSpadeBlue2.png",
      url3: "/img/kateSpadeBlue3.png",
      description:
        "Kate Spade dark blue plastic glasses with gold temples. Big lens size and will easily fit a progressive. New style, fun and fabulous.",
    },
    {
      name: "Dior Pink/red Sunglasses",
      category: "Sunglasses",
      id: "6",
      price: "275",
      size: "53-19",
      brand: "Dior",
      url: "/img/pinkDior.png",
      url1: "/img/pinkDior1.png",
      url2: "/img/pinkDior2.png",
      description:
        "Fun and great fitting Dior sunglasses. Perfect for everyday and fit beautifully. Reddish front frame and dark blue temples",
    },
    {
      name: "Prada dark brown tortoise frames",
      category: "Glasses",
      id: "7",
      price: "225",
      size: "55-16",
      brand: "Prada",
      url: "/img/grayMattePrada.png",
      url1: "/img/grayMattePrada1.png",
      url2: "/img/grayMattePrada2.png",
      url3: "/img/grayMattePrada3.png",
      description:
        "PRADA New with tag brown tortoise frames. Not shiny, but Brushed like front. Great rectangle style & shape - size 55-16. Temples say Prada on them and super cool",
    },
    {
      name: "Emporio Armani brown tortoise sunglasses",
      category: "Sunglasses",
      id: "8",
      price: "165",
      size: "One size",
      brand: "Emporio Armani",
      url: "/img/brownEmpirio.png",
      url1: "/img/brownEmpirio1.png",
      url2: "/img/brownEmpirio2.png",
      url3: "/img/brownEmpirio3.png",
      description:
        "Emporia brown tortoise round sunglasses with lots of protection. The temples are a brushed gold and brown as picture indicates. Front is large and roundish. High fashion",
    },
    {
      name: "Kate Spade brown tortoise glasses",
      category: "Glasses",
      id: "9",
      price: "159",
      size: "50-16",
      brand: "Kate Spade",
      url: "/img/kateSpadeTortoise.png",
      url1: "/img/kateSpadeTortoise1.png",
      url2: "/img/kateSpadeTortoise2.png",
      url3: "/img/kateSpadeTortoise3.png",
      description:
        "Kate Spade small size/fit tortoise glasses. Super cute and comfortable. Tortoise front with black temple-100% authentic.",
    },
    {
      name: "Kate Spade black sunglasses",
      category: "Sunglasses",
      id: "10",
      price: "175",
      size: "One Size",
      brand: "Kate Spade",
      url: "/img/pinkCase.png",
      url1: "/img/pinkCase1.png",
      url2: "/img/pinkCase2.png",
      url3: "/img/pinkCase3.png",
      description:
        "Kate spade new york Hello Sunshine big black sunglasses with black temples and a little beige/taupe on the side. Stylish and fun.",
    },
    {
      name: "Silhouette lavendar/lilac rimless frames",
      category: "Glasses",
      id: "11",
      price: "175",
      size: "49 17 135",
      brand: "Silhouette",
      url: "/img/purpleSilhouette.png",
      url1: "/img/purpleSilhouette1.png",
      url2: "/img/purpleSilhouette2.png",
      description:
        "Beautiful lightweight lilac colored titanium rimless glasses. Super comfortable and easy to wear.",
    },
    {
      name: "Coach brown tortoise sunglasses",
      category: "Sunglasses",
      id: "12",
      price: "175",
      size: "One size",
      brand: "Coach",
      url: "/img/coachBrown.png",
      url1: "/img/coachBrown1.png",
      url2: "/img/coachBrown2.png",
      url3: "/img/coachBrown3.png",
      description:
        "Big brown tortoise sunglasses with full coverage. 100% authentic and UV protection. Stylish and fun. Great logo on the side. Coach case not included… but will provide a sunglass case.",
    },
    {
      name: "Michael Kors gunmetal silver frames",
      category: "Glasses",
      id: "13",
      price: "155",
      size: "54",
      brand: "Michael Kors",
      url: "/img/mkSilverFrame.png",
      url1: "/img/mkSilverFrame1.png",
      url2: "/img/mkSilverFrame2.png",
      url3: "/img/mkSilverFrame3.png",
      description:
        "Michael Kors full frame in gunmetal silver color with MIchael Kors logo on temples. Temples have some brown tortoise near ear piece- picture enclosed. Eye size 54. Progressive will fit into these, if need be.",
    },
    {
      name: "Rag & Bone sunglasses",
      category: "Sunglasses",
      id: "14",
      price: "195",
      size: "56-19-145",
      brand: "Rag & Bone",
      url: "/img/rag&Bone.png",
      url1: "/img/rag&Bone1.png",
      url2: "/img/rag&Bone2.png",
      url3: "/img/rag&Bone3.png",
      description:
        "Rag & bone white marbled large flash mirror lens. Super fun, trendy and comfortable. Perfect for summer. Great sun protection",
    },
    {
      name: "Silhouette blue rimless frames",
      category: "Glasses",
      id: "15",
      price: "175",
      size: "53 17 135",
      brand: "Silhouette",
      url: "/img/blueSilhouette.png",
      url1: "/img/blueSilhouette1.png",
      url2: "/img/blueSilhouette2.png",
      url3: "/img/blueSilhouette3.png",
      description:
        "Beautiful teal colored silhouette rimless glasses. Light and comfortable on your face. Fashionable and fun",
    },
  ],
  navs: [
    {
      name: "Sunglasses",
    },
    {
      name: "Glasses",
    },
  ],
};
